<?php
/**
 * status.php — Job Status Polling Endpoint
 *
 * Called by the frontend every 2 seconds via fetch().
 * Returns JSON with:
 *   - status   : running | completed | failed
 *   - log      : full log file contents so far
 *   - summary  : { passed, failed, skipped } (extracted from log when complete)
 *   - pdf      : true/false — does the PDF report exist?
 *   - txt      : true/false — does the TXT report exist?
 */

session_start();
header('Content-Type: application/json');
header('Cache-Control: no-cache');

// ── Auth guard ────────────────────────────────────────────────────────────────
if (empty($_SESSION['authenticated'])) {
    http_response_code(403);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}

// ── Validate and sanitise jobId ───────────────────────────────────────────────
// Job IDs are generated by run.php in format: <word>_YYYYMMDD_HHMMSS
// We strip anything that doesn't match to prevent path traversal.
$rawJobId = $_GET['jobId'] ?? '';
$jobId    = preg_replace('/[^a-z0-9_]/i', '', $rawJobId);

if (empty($jobId)) {
    http_response_code(400);
    echo json_encode(['error' => 'Missing or invalid jobId']);
    exit;
}

define('LOGS_DIR',    __DIR__ . DIRECTORY_SEPARATOR . 'logs');
define('REPORTS_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'reports');

// Source report paths (generated by the Java/TestNG listener)
define('MAVEN_REPORTS_DIR', 'C:\xampp\htdocs\Online Furniture Shop Project\ofsms\automation\target\reports');

$statusFile = LOGS_DIR . DIRECTORY_SEPARATOR . $jobId . '.status';
$logFile    = LOGS_DIR . DIRECTORY_SEPARATOR . $jobId . '.txt';

// ── Check that the job files exist ───────────────────────────────────────────
if (!file_exists($statusFile)) {
    echo json_encode(['error' => 'Job not found: ' . $jobId]);
    exit;
}

// ── Read current status ───────────────────────────────────────────────────────
$status = trim(file_get_contents($statusFile));
$status = in_array($status, ['running', 'completed', 'failed'], true) ? $status : 'failed';

// ── Read log contents ─────────────────────────────────────────────────────────
$logContent = file_exists($logFile) ? file_get_contents($logFile) : '';

// ── Check for report files ────────────────────────────────────────────────────
// When status transitions to complete, attempt to copy reports from Maven's
// target/reports directory into our /reports folder so they can be served.
$pdfExists = false;
$txtExists = false;

$localPdf = REPORTS_DIR . DIRECTORY_SEPARATOR . $jobId . '.pdf';
$localTxt = REPORTS_DIR . DIRECTORY_SEPARATOR . $jobId . '.txt';

if ($status === 'completed' || $status === 'failed') {
    // Copy PDF from Maven output if not already copied
    if (!file_exists($localPdf)) {
        $sourcePdf = MAVEN_REPORTS_DIR . DIRECTORY_SEPARATOR . $jobId . '.pdf';
        if (file_exists($sourcePdf)) {
            copy($sourcePdf, $localPdf);
        }
    }
    // Copy TXT from Maven output if not already copied
    if (!file_exists($localTxt)) {
        $sourceTxt = MAVEN_REPORTS_DIR . DIRECTORY_SEPARATOR . $jobId . '.txt';
        if (file_exists($sourceTxt)) {
            copy($sourceTxt, $localTxt);
        }
    }

    $pdfExists = file_exists($localPdf);
    $txtExists = file_exists($localTxt);
}

// ── Parse test summary from log / report ─────────────────────────────────────
$summary = null;

if ($status !== 'running') {
    $summary = parseSummary($logContent, $localTxt);
}

// ── Build response ────────────────────────────────────────────────────────────
echo json_encode([
    'jobId'   => $jobId,
    'status'  => $status,
    'log'     => $logContent,
    'summary' => $summary,
    'pdf'     => $pdfExists,
    'txt'     => $txtExists,
]);

// ════════════════════════════════════════════════════════════════════════════
// HELPERS
// ════════════════════════════════════════════════════════════════════════════

/**
 * parseSummary()
 *
 * Attempts to extract pass/fail/skip counts from multiple sources:
 *   1. A companion JSON summary file generated by the TestNG listener
 *   2. Maven Surefire's standard "Tests run: X, Failures: Y, Errors: Z, Skipped: W" line
 *   3. TestNG's own summary line format
 *
 * Returns array ['passed'=>int, 'failed'=>int, 'skipped'=>int] or null.
 */
function parseSummary(string $logContent, string $localTxtPath): ?array
{
    // ── Strategy 1: JSON summary file (preferred) ─────────────────────────────
    // Your TestNG listener should write a <jobId>.json file alongside the PDF/TXT.
    // Expected format: {"passed":42,"failed":3,"skipped":1}
    $jsonFile = str_replace('.txt', '.json', $localTxtPath);
    if (file_exists($jsonFile)) {
        $data = json_decode(file_get_contents($jsonFile), true);
        if (is_array($data) && isset($data['passed'])) {
            return [
                'passed'  => (int)($data['passed']  ?? 0),
                'failed'  => (int)($data['failed']  ?? 0),
                'skipped' => (int)($data['skipped'] ?? 0),
            ];
        }
    }

    // ── Strategy 2: Maven Surefire output ────────────────────────────────────
    // Example: Tests run: 50, Failures: 2, Errors: 1, Skipped: 3
    if (preg_match(
        '/Tests run:\s*(\d+),\s*Failures:\s*(\d+),\s*Errors:\s*(\d+),\s*Skipped:\s*(\d+)/i',
        $logContent, $m
    )) {
        $total   = (int)$m[1];
        $failed  = (int)$m[2] + (int)$m[3];
        $skipped = (int)$m[4];
        $passed  = $total - $failed - $skipped;
        return [
            'passed'  => max(0, $passed),
            'failed'  => $failed,
            'skipped' => $skipped,
        ];
    }

    // ── Strategy 3: TestNG summary line ──────────────────────────────────────
    // Example: Total tests run: 50, Passes: 45, Failures: 3, Skips: 2
    if (preg_match(
        '/Total tests run:\s*(\d+),\s*Passes:\s*(\d+),\s*Failures:\s*(\d+),\s*Skips:\s*(\d+)/i',
        $logContent, $m
    )) {
        return [
            'passed'  => (int)$m[2],
            'failed'  => (int)$m[3],
            'skipped' => (int)$m[4],
        ];
    }

    return null; // Could not determine summary
}
